#-------------------------------
# General Site Settings
title: LKBrilliant
logo: # You can add own logo.
description: Showcase of my projects


#-------------------------------
# Author Settings
author:
  name: Anuradha Gunawardhana
  image: Under_Construction.jpg
  say-hello: Hello, <br> I’m <strong>Anuradha Gunawardhana</strong>
  bio: I'm a <strong>Designer</strong>, <strong>Maker</strong>, and <strong>Electronics enthusiast</strong> who likes to build things and document them.


#-------------------------------
# Contact links
twitter: https://twitter.com/LKBrilliant
github: https://github.com/LKbrilliant
email: mailto:contact.lkbrilliant@gmail.com
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
